name: itech3209
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Breathless.png
    - assets/background_main.jpg
    - assets/Butterflies.png
    - assets/mascot_fox.png
    - assets/mascot_lizard.png
    - assets/mascot_shark.png
    - assets/Bloated.png
    - assets/Dry.png
    - assets/Gassy.png
    - assets/Growling.png
    - assets/Nauseous.png
    - assets/Want to move.png
    - assets/Wobbly.png
    - assets/Cramp.png
    - assets/bodycheck.png
    - assets/stomach.png
    - assets/head.png
    - assets/body.png
    - assets/arm.png
    - assets/leg.png
    - assets/foot.png

